name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Extract version from tag
        id: get_version
        run: |
          # Remove 'v' prefix from tag if present (e.g., v1.0.0 -> 1.0.0)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update version in pyproject.toml
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          echo "Updated pyproject.toml version to $VERSION"
          cat pyproject.toml | grep "version ="

      - name: Build package
        run: |
          python -m build
          echo "Built packages:"
          ls -la dist/

      - name: Check package
        run: |
          python -m twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/*

      - name: Verify publication
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          echo "Package published successfully!"
          echo "Install with: pip install laplace-python-sdk==$VERSION"
          echo "PyPI URL: https://pypi.org/project/laplace-python-sdk/$VERSION/"
